spring:
  application:
    name: ${SPRING_APP_NAME:eazybankbackend}
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3308}/${DATABASE_NAME:eazybank}
    username: ${DB_USER:root}
    password: ${DB_PWD:root}
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
#    hibernate:
#      ddl-auto: create-drop
  config:
    import: application-prod.yaml
  profiles:
    active: ${SPRING_PROFILE:prod}
  security:
    oauth2:
      # JWT based
      authorizationserver:
        endpoint:
          # Spring Oauth2 server
          jwk-set-uri: http://localhost:9000/oauth2/jwks
          # Keycloak
      #          jwk-set-uri: http://localhost:8180/realms/eazybankdev/protocol/openid-connect/certs
      resourceserver:
        jwt:
          # Spring Oauth2 server
          issuer-uri: http://localhost:9000
          # Keycloak
#          issuer-uri: http://localhost:8180/realms/eazybankdev

#      # Opaque token
#      resourceserver:
#        opaquetoken:
#          # Keycloak
##          client-id: eazybankintrospect
##          client-secret: 5MI1L0Mk5GtsZdm7mL4fBevlom7hziyI
##          introspection-uri: http://localhost:8180/realms/eazybankdev/protocol/openid-connect/token/introspect
#          client-id: eazybankintrospect
#          client-secret: 5MI1L0Mk5GtsZdm7mL4fBevlom7hziyI
#          introspection-uri: http://localhost:9000/oauth2/introspect


#  security:
#    user:
#      password: pwd

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}

server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:20m}