spring:
  application:
    name: ${SPRING_APP_NAME:eazybankbackend}
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3308}/${DATABASE_NAME:eazybank}
    username: ${DB_USER:root}
    password: ${DB_PWD:root}
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:false}
#    hibernate:
#      ddl-auto: create-drop
#  security:
#    user:
#      password: pwd
  security:
    oauth2:
      authorizationserver:
        endpoint:
          jwk-set-uri: http://localhost:8180/realms/eazybankdev/protocol/openid-connect/certs
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/eazybankdev
logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:ERROR}
server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:20m}